-- 0005_audit_log.sql
-- Append-only audit trail on every business table (ADR-020: SOC 2
-- change-tracking evidence built now, certification paperwork later).
--
-- GDPR takes precedence over audit retention: erase_person() purges audit
-- entries referencing the erased person — an audit log must never resurrect
-- erased data (ADR-008/012). Merge recovery evidence lives in merge_log;
-- erasure evidence is the suppression_list entry.

create table audit_log (
  id          bigint generated always as identity primary key,
  occurred_at timestamptz not null default now(),
  actor       text not null default current_user,
  table_name  text not null,
  op          text not null check (op in ('INSERT', 'UPDATE', 'DELETE')),
  row_id      uuid,
  old_row     jsonb,
  new_row     jsonb
);

create index audit_log_row_idx on audit_log (table_name, row_id);
create index audit_log_occurred_at_idx on audit_log (occurred_at);

alter table audit_log enable row level security;

-- Embeddings are stripped from captured rows: 12KB of vector per person
-- update is cost without evidence value.
create function audit_row_change() returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
declare
  v_old jsonb;
  v_new jsonb;
begin
  if tg_op in ('UPDATE', 'DELETE') then v_old := to_jsonb(old) - 'embedding'; end if;
  if tg_op in ('INSERT', 'UPDATE') then v_new := to_jsonb(new) - 'embedding'; end if;
  insert into audit_log (actor, table_name, op, row_id, old_row, new_row)
  values (current_user, tg_table_name, tg_op,
          coalesce((v_new ->> 'id')::uuid, (v_old ->> 'id')::uuid),
          v_old, v_new);
  return coalesce(new, old);
end;
$$;

-- Business tables only. Not audited: merge_log (is itself an audit
-- artifact), ai_usage_log (append-only telemetry), audit_log (obviously).
create trigger person_audit after insert or update or delete on person
  for each row execute function audit_row_change();
create trigger person_email_audit after insert or update or delete on person_email
  for each row execute function audit_row_change();
create trigger company_audit after insert or update or delete on company
  for each row execute function audit_row_change();
create trigger company_domain_audit after insert or update or delete on company_domain
  for each row execute function audit_row_change();
create trigger employment_audit after insert or update or delete on employment
  for each row execute function audit_row_change();
create trigger mandate_audit after insert or update or delete on mandate
  for each row execute function audit_row_change();
create trigger candidacy_audit after insert or update or delete on candidacy
  for each row execute function audit_row_change();
create trigger deal_audit after insert or update or delete on deal
  for each row execute function audit_row_change();
create trigger activity_audit after insert or update or delete on activity
  for each row execute function audit_row_change();
create trigger activity_participant_audit after insert or update or delete on activity_participant
  for each row execute function audit_row_change();
create trigger document_audit after insert or update or delete on document
  for each row execute function audit_row_change();
create trigger merge_queue_audit after insert or update or delete on merge_queue
  for each row execute function audit_row_change();
create trigger counterparty_queue_audit after insert or update or delete on counterparty_queue
  for each row execute function audit_row_change();
create trigger suppression_list_audit after insert or update or delete on suppression_list
  for each row execute function audit_row_change();
create trigger ingestion_state_audit after insert or update or delete on ingestion_state
  for each row execute function audit_row_change();
create trigger ingestion_dead_letter_audit after insert or update or delete on ingestion_dead_letter
  for each row execute function audit_row_change();

-- ---------------------------------------------------------------------------
-- erase_person: 0002 two-path version + audit purge. The purge runs last so
-- audit rows generated by the erasure itself are also removed.
-- ---------------------------------------------------------------------------

create or replace function erase_person(p_person uuid)
returns void
language plpgsql
set search_path = public, pg_temp
as $$
declare
  v_placed boolean;
  v_sole_activities uuid[];
begin
  perform 1 from person where id = p_person for update;
  if not found then
    raise exception 'erase_person: person % not found', p_person;
  end if;

  -- Both paths: hash every known email into the suppression list so
  -- ingestion can never resurrect this person (ADR-008).
  insert into suppression_list (email_hash, reason)
  select encode(digest(lower(e.email::text), 'sha256'), 'hex'), 'erased'
  from person_email e
  where e.person_id = p_person
  on conflict (email_hash) do nothing;

  -- Both paths: activities where this person was the sole participant are
  -- deleted outright; multi-party activities keep their content. Their ids
  -- are kept so the audit purge below can also remove their audit entries —
  -- activity rows carry no person_id for the purge to match on.
  select coalesce(array_agg(a.id), '{}') into v_sole_activities
  from activity a
  where exists (select 1 from activity_participant ap
                where ap.activity_id = a.id and ap.person_id = p_person)
    and not exists (select 1 from activity_participant ap2
                    where ap2.activity_id = a.id and ap2.person_id <> p_person);

  delete from activity where id = any(v_sole_activities);

  -- placed_at is the durable placement marker: a later stage correction or
  -- regression must not route a real placement to the hard-delete path.
  select exists (
    select 1 from candidacy c
    where c.person_id = p_person
      and (c.stage = 'placed' or c.placed_at is not null)
  ) into v_placed;

  if not v_placed then
    -- Never placed: full hard delete with cascades, as in 0001.
    delete from person where id = p_person;
  else
    -- Placed: redacted erasure. Only the placement lineage survives.
    delete from activity_participant where person_id = p_person;
    delete from document where person_id = p_person;
    delete from person_email where person_id = p_person;
    delete from employment where person_id = p_person;
    delete from candidacy
    where person_id = p_person and stage <> 'placed' and placed_at is null;
    -- The surviving rows are an anonymised statutory record: free-text notes
    -- can identify the person, so they do not survive (ADR-012).
    update candidacy set notes = null where person_id = p_person;
    delete from merge_queue where person_a = p_person or person_b = p_person;
    update deal set primary_contact_id = null where primary_contact_id = p_person;

    update person set
      full_name        = '[erased]',
      linkedin_url     = null,
      location         = null,
      profile          = null,
      consent_override = null,
      embedding        = null,
      erased_at        = now()
    where id = p_person;
  end if;

  -- GDPR over audit retention (ADR-020): remove every audit entry that
  -- references the erased person, including entries generated above.
  delete from audit_log
  where row_id = p_person
     or row_id = any(v_sole_activities)
     or old_row ->> 'person_id' = p_person::text
     or new_row ->> 'person_id' = p_person::text
     or old_row ->> 'primary_contact_id' = p_person::text
     or new_row ->> 'primary_contact_id' = p_person::text
     or old_row ->> 'person_a' = p_person::text
     or new_row ->> 'person_a' = p_person::text
     or old_row ->> 'person_b' = p_person::text
     or new_row ->> 'person_b' = p_person::text;
end;
$$;
